export const MUSCLES = ["Chest", "Back", "Shoulders", "Arms", "Legs", "Core"];
export const MAX_EXERCISES = 8;
const ex = (id, name, muscle, equipment, sets, min, max, rest, tip) => ({
  id,
  name,
  muscle,
  equipment,
  sets,
  min,
  max,
  rest,
  tip,
});
export const EXERCISES = {
  bench: ex(
    "bench",
    "Barbell bench press",
    "Chest",
    "Barbell",
    3,
    8,
    10,
    90,
    "Keep your feet planted and lower the bar with control.",
  ),
  incline: ex(
    "incline",
    "Incline dumbbell press",
    "Chest",
    "Dumbbells",
    3,
    10,
    12,
    75,
    "Use a low incline. Keep your shoulder blades gently back.",
  ),
  fly: ex(
    "fly",
    "Cable chest fly",
    "Chest",
    "Cable",
    2,
    12,
    15,
    60,
    "Keep a soft bend in your elbows throughout the movement.",
  ),
  row: ex(
    "row",
    "Seated cable row",
    "Back",
    "Cable",
    3,
    10,
    12,
    75,
    "Pull toward your lower ribs without rocking your torso.",
  ),
  pulldown: ex(
    "pulldown",
    "Lat pulldown",
    "Back",
    "Cable",
    3,
    10,
    12,
    75,
    "Drive your elbows down and keep your chest tall.",
  ),
  dbrow: ex(
    "dbrow",
    "Dumbbell row",
    "Back",
    "Dumbbells",
    3,
    8,
    12,
    75,
    "Support your torso and complete each side with control.",
  ),
  press: ex(
    "press",
    "Dumbbell shoulder press",
    "Shoulders",
    "Dumbbells",
    3,
    8,
    10,
    90,
    "Keep your ribs down and press through a comfortable range.",
  ),
  lateral: ex(
    "lateral",
    "Dumbbell lateral raise",
    "Shoulders",
    "Dumbbells",
    2,
    12,
    15,
    60,
    "Lead with your elbows and avoid swinging the weight.",
  ),
  facepull: ex(
    "facepull",
    "Cable face pull",
    "Shoulders",
    "Cable",
    2,
    12,
    15,
    60,
    "Pull toward eye level while keeping your shoulders relaxed.",
  ),
  curl: ex(
    "curl",
    "Dumbbell biceps curl",
    "Arms",
    "Dumbbells",
    2,
    10,
    12,
    60,
    "Keep your elbows close to your sides.",
  ),
  triceps: ex(
    "triceps",
    "Rope triceps pushdown",
    "Arms",
    "Cable",
    2,
    10,
    12,
    60,
    "Keep your upper arms still and extend your elbows smoothly.",
  ),
  squat: ex(
    "squat",
    "Barbell back squat",
    "Legs",
    "Barbell",
    3,
    8,
    10,
    120,
    "Brace your trunk and use a depth you can control.",
  ),
  rdl: ex(
    "rdl",
    "Romanian deadlift",
    "Legs",
    "Barbell",
    3,
    8,
    10,
    120,
    "Push your hips back with a slight bend in your knees.",
  ),
  legpress: ex(
    "legpress",
    "Leg press",
    "Legs",
    "Machine",
    3,
    10,
    12,
    90,
    "Keep your hips on the pad and avoid locking your knees.",
  ),
  lunge: ex(
    "lunge",
    "Reverse dumbbell lunge",
    "Legs",
    "Dumbbells",
    3,
    10,
    12,
    90,
    "Reps are per side. Step back and keep the front foot planted.",
  ),
  legcurl: ex(
    "legcurl",
    "Seated leg curl",
    "Legs",
    "Machine",
    3,
    10,
    12,
    75,
    "Keep your hips down and control the return.",
  ),
  calf: ex(
    "calf",
    "Standing calf raise",
    "Legs",
    "Machine",
    2,
    12,
    15,
    60,
    "Pause briefly at the top and lower your heels slowly.",
  ),
  deadbug: ex(
    "deadbug",
    "Dead bug",
    "Core",
    "Bodyweight",
    3,
    10,
    12,
    45,
    "Reps are per side. Keep your lower back gently against the floor.",
  ),
  crunch: ex(
    "crunch",
    "Cable crunch",
    "Core",
    "Cable",
    3,
    12,
    15,
    60,
    "Curl through your trunk without pulling with your arms.",
  ),
};
